<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE livres [<!ELEMENT livres (livre)+>

<!ELEMENT livre (auteur,titre)>
<!ATTLIST livre
genre CDATA #REQUIRED
isbn CDATA #REQUIRED>

<!ELEMENT auteur (prenom,nomDeFamille)>
<!ATTLIST auteur
nationalite NMTOKEN #REQUIRED>

<!ELEMENT titre (#PCDATA)>

<!ELEMENT prenom (#PCDATA)>

<!ELEMENT nomDeFamille (#PCDATA)>

]>

<livres>
    <livre isbn="00000" genre="science-fiction">
        <auteur nationalite="zho">
            <prenom>Cixin</prenom>
            <nomDeFamille>Liu</nomDeFamille>
        </auteur>
        <titre>The Three-Body problem</titre>
    </livre>
    <livre isbn="00001" genre="tragédie gothique">
        <auteur nationalite="eng">
            <prenom>Emily</prenom>
            <nomDeFamille>Brontë</nomDeFamille>
        </auteur>
        <titre>Wuthering Heights</titre>
    </livre>
</livres>